# Generated by Django 4.2.3 on 2023-09-12 12:25

from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('profile_pic', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
            ],
            options={
                'verbose_name_plural': 'Parent',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('guardian', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=13)),
                ('bloodGroup', models.CharField(max_length=3)),
                ('subjects', models.ManyToManyField(to='study.subject')),
            ],
            options={
                'verbose_name_plural': 'Teacher',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('emergency_contact', models.CharField(max_length=13)),
                ('bloodGroup', models.CharField(max_length=3)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.parent')),
                ('subjects', models.ManyToManyField(to='study.subject')),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
            bases=('users.user',),
            managers=[
                ('objects', users.managers.CustomUserManager()),
            ],
        ),
    ]
